// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use PRISMA_CLI_DATABASE_URL for CLI commands (prisma db push, prisma dev)
    // Falls back to DATABASE_URL for local direct postgres
    url: process.env["PRISMA_CLI_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
